export const LUDO_THEMES = [
  {
    id: 'theme-royal-emerald',
    name: 'Royal Emerald',
    className: 'theme-royal-emerald',
    image: '/ludo-images/bg_game.jpg',
    boardBg: '/ludo-images/bg_game.jpg',
    description: 'Classic royal velvet texture with rich emerald styling',
    colors: {
      red: '#ef4444',
      green: '#22c55e',
      yellow: '#eab308',
      blue: '#3b82f6',
    },
  },
  {
    id: 'theme-cyber-neon',
    name: 'Cyber Neon',
    className: 'theme-cyber-neon',
    image: '/ludo-images/bg_game2.png',
    boardBg: '/ludo-images/bg_game2.png',
    description: 'Electric midnight cyberpunk arena with glowing tracks',
    colors: {
      red: '#ff007f',
      green: '#39ff14',
      yellow: '#fcf601',
      blue: '#00ffff',
    },
  },
  {
    id: 'theme-desert-palace',
    name: 'Desert Palace',
    className: 'theme-desert-palace',
    image: '/ludo-images/bg_game3.png',
    boardBg: '/ludo-images/bg_game3.png',
    description: 'Luxurious desert gold arena with ornate wooden patterns',
    colors: {
      red: '#dc2626',
      green: '#16a34a',
      yellow: '#f59e0b',
      blue: '#2563eb',
    },
  },
  {
    id: 'theme-cosmic-galaxy',
    name: 'Cosmic Galaxy',
    className: 'theme-cosmic-galaxy',
    image: '/ludo-images/bg_game4.png',
    boardBg: '/ludo-images/bg_game4.png',
    description: 'Deep astral realm with starlight nebula styling',
    colors: {
      red: '#f43f5e',
      green: '#10b981',
      yellow: '#fbbf24',
      blue: '#6366f1',
    },
  },
];
